0.5	ROOT	S .
0.2	ROOT	S !
0.3	ROOT	is it true that S ?

1	S	NP VP
1	VP	Verb NP
0.4	NP	Det Noun
0.6	NP	NP PP
1	PP	Prep NP
0.5	Noun	Adj Noun

0.2	Verb	ate
0.2	Verb	wanted
0.2	Verb	kissed
0.2	Verb	understood
0.2	Verb	pickled

0.5	Det	the
0.4	Det	a
0.1	Det	every

0.1	Noun	president
0.1	Noun	sandwich
0.1	Noun	pickle
0.1	Noun	chief of staff
0.1	Noun	floor

0.3	Adj	fine
0.3	Adj	delicious
0.2	Adj	perplexed
0.2	Adj	pickled

0.3	Prep	with
0.2	Prep	on
0.4	Prep	under
0.1	Prep	in
